### ISSUE TITLE
[question] is this project still working? after #7 update?

### ISSUE THREAD

**Issue by mobilelifeful** [ThisIsQasim/TastyIgniter#9]
First:
`docker compose up -d`
then 
`docker compose exec app php artisan igniter:install --no-interaction`
finally
`docker compose exec app php artisan igniter:passwd admin`
![image](https://github.com/ThisIsQasim/TastyIgniter/assets/91811647/cc07ceaa-23bf-478e-b27a-98e7c54369f9)
given:

```
root@vps:~/TastyIgniter# cat docker-compose.yml
version: '2'
services:
  app:
    image: thisisqasim/tastyigniter:3.4.0
    hostname: tasty
    ports:
      - 8001:80
    environment:
      - APP_URL=https://www.mydomain.tld
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_DATABASE=tastyigniter
      - DB_USERNAME=tastyigniter
      - DB_PASSWORD=somepassword
      - CACHE_DRIVER=redis
      - REDIS_HOST=redis
    restart: always
  db:
    image: mariadb:10.7
    volumes:
      - ./db:/var/lib/mysql
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=tastyigniter
      - MYSQL_USER=tastyigniter
      - MYSQL_PASSWORD=somepassword
    restart: always
  redis:
    image: redis:6
    command: redis-server --maxmemory 256mb --maxmemory-policy allkeys-lru
    restart: always
root@vps:~/TastyIgniter#

```
Do we still need to config nginx in order to visit www.mydomain.tld ?  Thank you in advance.
